---
version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/roles/platform/files/ingress/docker-compose.yml"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker-compose"
    directory: "/roles/platform/files/monitoring/docker-compose.yml"
    schedule:
      interval: "daily"
