---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Disable UFW firewall and flush rules
  when:
    - ansible_facts.services['ufw.service'] is defined
    - ansible_facts.services['ufw.service'].state == 'running'
  community.general.ufw:
    state: disabled

- name: Disable Firewalld
  when:
    - ansible_facts.services['firewalld.service'] is defined
    - ansible_facts.services['firewalld.service'].state == 'running'
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
