---
- name: Ensure the platform ingress folder exists
  ansible.builtin.file:
    path: "{{ platform__ingress_folder }}"
    state: directory
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

- name: Synchronize platform ingress docker compose
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/ingress/"
    dest: "{{ platform__ingress_folder }}"
    recursive: true
    checksum: true
    rsync_opts:
      - "--chmod=755"

- name: Generate the .env file for the platform docker compose
  ansible.builtin.copy:
    dest: "{{ platform__ingress_folder }}.env"
    content: |
      BASE_DOMAIN={{ platform__base_domain }}
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

    # note: we will not rerun docker compose up on the ingress to avoid downtime
    # TODO:
    # - check if ingress is up.
    # - if ingress is not up, run docker compose up
    # - if docker compose command failed, print stdout|stderr
