---
- name: ingress - Ensure the compose folder exists
  ansible.builtin.file:
    path: "{{ platform__ingress_folder }}"
    state: directory
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

- name: ingress - Synchronize the compose folder
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/ingress/"
    dest: "{{ platform__ingress_folder }}"
    recursive: true
    checksum: true
    rsync_opts:
      - "--chmod=755"

- name: ingress - Generate the .env file for the docker compose
  ansible.builtin.copy:
    dest: "{{ platform__ingress_folder }}.env"
    content: |
      BASE_DOMAIN={{ platform__base_domain }}
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

# note: We don't want to rerun 'docker compose up' on the ingress to avoid downtime.
# This is why the following steps perform the following actions:
# - check if the ingress is up.
# - Only when the ingress is NOT up, run docker compose up
# - if docker compose command didn't fail, print stdout|stderr

- name: ingress - Get all active docker compose services
  ansible.builtin.command: >
    docker ps
      --filter "label=com.docker.compose.project"
     {% raw %}
      --format '{{.Label "com.docker.compose.project.working_dir"}}'
     {% endraw %}
  register: fact__active_services
  changed_when: false

- name: ingress - Check if the compose service is up
  set_fact:
    fact__ingress_service_is_up: >-
      {{
        ( platform__ingress_folder | regex_replace('/$', '')
        in fact__active_services.stdout_lines) | bool
      }}

- name: ingress - Start docker compose service
  when: not fact__ingress_service_is_up
  block:
    - name: ingress - Start docker compose service
      command: docker compose up -d
      args:
        chdir: "{{ platform__ingress_folder }}"
      register: compose_result
      failed_when: compose_result.rc != 0
      changed_when: compose_result.rc == 0

    - name: ingress - Print compose up stdout
      debug:
        msg: "{{ compose_result.stdout }}"

    - name: ingress - Print compose up stderr
      debug:
        msg: "{{ compose_result.stderr }}"
