---
- name: Ensure the platform monitoring folder exists
  ansible.builtin.file:
    path: "{{ platform__monitoring_folder }}"
    state: directory
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

- name: Synchronize platform monitoring docker compose
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/monitoring/"
    dest: "{{ platform__monitoring_folder }}"
    recursive: true
    checksum: true
    rsync_opts:
      - "--chmod=755"

- name: Generate the .env file for the platform docker compose
  ansible.builtin.copy:
    dest: "{{ platform__monitoring_folder }}.env"
    content: |
      BASE_DOMAIN={{ platform__base_domain }}
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

    # TODO:
    # - check if previous fsync changed
    # - check if compose is up
    # - if compose is down, or if files changed, run docker compose up again
    # - if docker compose command failed, print stdout|stderr
