---
- name: List all docker networks
  ansible.builtin.command: docker network ls --format '{{ "{{.Name}}" }}'
  register: all_docker_networks
  changed_when: false

- name: Create the traefik-proxy Docker network if it doesn't exist
  ansible.builtin.command: docker network create traefik-proxy
  when: "'traefik-proxy' not in all_docker_networks.stdout_lines"
  changed_when: true

- name: Ensure the platform folder exists
  ansible.builtin.file:
    path: "{{ platform__folder }}"
    state: directory
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

- name: Synchronize platform docker compose
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ platform__folder }}"
    recursive: true
    delete: true       # deletes files in dest not present in src
    rsync_opts:
      - "--chmod=755"

- name: Generate the .env file for the platform docker compose
  ansible.builtin.copy:
    dest: "{{ platform__folder }}.env"
    content: |
      BASE_DOMAIN={{ platform__base_domain }}
    owner: "{{ platform__admin_name }}"
    group: "{{ platform__admin_name }}"
    mode: '0755'

    # - name: rerun docker compose
    #   shell: cd /home/al/control-plane && docker compose up -d
    #   register: output

    # - name: Show stdout
    #   ansible.builtin.debug:
    #     var: output.stdout_lines
    # - name: Show stderr
    #   ansible.builtin.debug:
    #     var: output.stderr_lines
