---
- name: Setup Docker network
  import_tasks: 010_network.yaml

- name: Manage the platform ingress
  import_tasks: 020_ingress.yaml

- name: Manage the platform monitoring stack
  import_tasks: 030_monitoring.yaml
  when:
    - platform__enable_monitoring
